"odpt.Railway:TokyoMetro.Ginza":
- "G01": "Shibuya"
- "G02": "OmoteSando"
- "G03": "Gaiemmae"
- "G04": "AoyamaItchome"
- "G05": "AkasakaMitsuke"
- "G06": "TameikeSanno"
- "G07": "Toranomon"
- "G08": "Shimbashi"
- "G09": "Ginza"
- "G10": "Kyobashi"
- "G11": "Nihombashi"
- "G12": "Mitsukoshimae"
- "G13": "Kanda"
- "G14": "Suehirocho"
- "G15": "UenoHirokoji"
- "G16": "Ueno"
- "G17": "Inaricho"
- "G18": "Tawaramachi"
- "G19": "Asakusa"
"odpt.Railway:TokyoMetro.Marunouchi":
- "m03": "Honancho"
- "m04": "NakanoFujimicho"
- "m05": "NakanoShimbashi"
- "M01": "Ogikubo"
- "M02": "MinamiAsagaya"
- "M03": "ShinKoenji"
- "M04": "HigashiKoenji"
- "M05": "ShinNakano"
- "M06": "NakanoSakaue"
- "M07": "NishiShinjuku"
- "M08": "Shinjuku"
- "M09": "ShinjukuSanchome"
- "M10": "ShinjukuGyoemmae"
- "M11": "YotsuyaSanchome"
- "M12": "Yotsuya"
- "M13": "AkasakaMitsuke"
- "M14": "KokkaiGijidomae"
- "M15": "Kasumigaseki"
- "M16": "Ginza"
- "M17": "Tokyo"
- "M18": "Otemachi"
- "M19": "Awajicho"
- "M20": "Ochanomizu"
- "M21": "HongoSanchome"
- "M22": "Korakuen"
- "M23": "Myogadani"
- "M24": "ShinOtsuka"
- "M25": "Ikebukuro"
"odpt.Railway:TokyoMetro.Hibiya":
- "H01": "NakaMeguro"
- "H02": "Ebisu"
- "H03": "HiroO"
- "H04": "Roppongi"
- "H05": "Kamiyacho"
- "H06": "Kasumigaseki"
- "H07": "Hibiya"
- "H08": "Ginza"
- "H09": "HigashiGinza"
- "H10": "Tsukiji"
- "H11": "Hatchobori"
- "H12": "Kayabacho"
- "H13": "Ningyocho"
- "H14": "Kodemmacho"
- "H15": "Akihabara"
- "H16": "NakaOkachimachi"
- "H17": "Ueno"
- "H18": "Iriya"
- "H19": "Minowa"
- "H20": "MinamiSenju"
- "H21": "KitaSenju"
"odpt.Railway:TokyoMetro.Tozai":
- "T01": "Nakano"
- "T02": "Ochiai"
- "T03": "Takadanobaba"
- "T04": "Waseda"
- "T05": "Kagurazaka"
- "T06": "Iidabashi"
- "T07": "Kudanshita"
- "T08": "Takebashi"
- "T09": "Otemachi"
- "T10": "Nihombashi"
- "T11": "Kayabacho"
- "T12": "MonzenNakacho"
- "T13": "Kiba"
- "T14": "Toyocho"
- "T15": "MinamiSunamachi"
- "T16": "NishiKasai"
- "T17": "Kasai"
- "T18": "Urayasu"
- "T19": "MinamiGyotoku"
- "T20": "Gyotoku"
- "T21": "Myoden"
- "T22": "BarakiNakayama"
- "T23": "NishiFunabashi"
"odpt.Railway:TokyoMetro.Chiyoda":
- "C01": "YoyogiUehara"
- "C02": "YoyogiKoen"
- "C03": "MeijiJingumae"
- "C04": "OmoteSando"
- "C05": "Nogizaka"
- "C06": "Akasaka"
- "C07": "KokkaiGijidomae"
- "C08": "Kasumigaseki"
- "C09": "Hibiya"
- "C10": "Nijubashimae"
- "C11": "Otemachi"
- "C12": "ShinOchanomizu"
- "C13": "Yushima"
- "C14": "Nezu"
- "C15": "Sendagi"
- "C16": "NishiNippori"
- "C17": "Machiya"
- "C18": "KitaSenju"
- "C19": "Ayase"
- "C20": "KitaAyase"
"odpt.Railway:TokyoMetro.Yurakucho":
- "Y01": "Wakoshi"
- "Y02": "ChikatetsuNarimasu"
- "Y03": "ChikatetsuAkatsuka"
- "Y04": "Heiwadai"
- "Y05": "Hikawadai"
- "Y06": "KotakeMukaihara"
- "Y07": "Senkawa"
- "Y08": "Kanamecho"
- "Y09": "Ikebukuro"
- "Y10": "HigashiIkebukuro"
- "Y11": "Gokokuji"
- "Y12": "Edogawabashi"
- "Y13": "Iidabashi"
- "Y14": "Ichigaya"
- "Y15": "Kojimachi"
- "Y16": "Nagatacho"
- "Y17": "Sakuradamon"
- "Y18": "Yurakucho"
- "Y19": "GinzaItchome"
- "Y20": "Shintomicho"
- "Y21": "Tsukishima"
- "Y22": "Toyosu"
- "Y23": "Tatsumi"
- "Y24": "ShinKiba"
"odpt.Railway:TokyoMetro.Hanzomon":
- "Z01": "Shibuya"
- "Z02": "OmoteSando"
- "Z03": "AoyamaItchome"
- "Z04": "Nagatacho"
- "Z05": "Hanzomon"
- "Z06": "Kudanshita"
- "Z07": "Jimbocho"
- "Z08": "Otemachi"
- "Z09": "Mitsukoshimae"
- "Z10": "Suitengumae"
- "Z11": "KiyosumiShirakawa"
- "Z12": "Sumiyoshi"
- "Z13": "Kinshicho"
- "Z14": "Oshiage"
"odpt.Railway:TokyoMetro.Namboku":
- "N01": "Meguro"
- "N02": "Shirokanedai"
- "N03": "ShirokaneTakanawa"
- "N04": "AzabuJuban"
- "N05": "RoppongiItchome"
- "N06": "TameikeSanno"
- "N07": "Nagatacho"
- "N08": "Yotsuya"
- "N09": "Ichigaya"
- "N10": "Iidabashi"
- "N11": "Korakuen"
- "N12": "Todaimae"
- "N13": "HonKomagome"
- "N14": "Komagome"
- "N15": "Nishigahara"
- "N16": "Oji"
- "N17": "OjiKamiya"
- "N18": "Shimo"
- "N19": "AkabaneIwabuchi"
"odpt.Railway:TokyoMetro.Fukutoshin":
- "F01": "Wakoshi"
- "F02": "ChikatetsuNarimasu"
- "F03": "ChikatetsuAkatsuka"
- "F04": "Heiwadai"
- "F05": "Hikawadai"
- "F06": "KotakeMukaihara"
- "F07": "Senkawa"
- "F08": "Kanamecho"
- "F09": "Ikebukuro"
- "F10": "Zoshigaya"
- "F11": "NishiWaseda"
- "F12": "HigashiShinjuku"
- "F13": "ShinjukuSanchome"
- "F14": "KitaSando"
- "F15": "MeijiJingumae"
- "F16": "Shibuya"