"Signup":
  "nickname": "メンバ登録"
  "counts":   0
  "stations": []
  "image":    "medal/medal-b.jpg"
"3visited":
  "nickname": "3駅訪問"
  "counts":   3
  "stations": []
  "image":    "medal/medal-s.jpg"
"10visited":
  "nickname": "10駅訪問"
  "counts":   10
  "stations": []
  "image":    "medal/medal-g.jpg"
"48visited":
  "nickname": "MTB48（48駅訪問）"
  "counts":   48
  "stations": []
  "image":    "trophy/mtb48.jpg"
"YoyogiMaster":
  "nickname": "代々木マスター"
  "counts":   2
  "stations": [YoyogiUehara, YoyogiKoen]
  "image":    "trophy/trophy-b.jpg"
"ShinjukuMaster":
  "nickname": "新宿マスター"
  "counts":   5
  "stations": [Shinjuku, ShinjukuGyoemmae, ShinjukuSanchome, NishiShinjuku, HigashiShinjuku]
  "image":    "trophy/trophy-s.jpg"
"TempleMaster":
  "nickname": "寺マスター"
  "counts":   3
  "stations": [ShinKoenji, HigashiKoenji, Gokokuji]
  "image":    "trophy/trophy-b.jpg"
"GateMaster":
  "nickname": "門マスター"
  "counts":   4
  "stations": [Sakuradamon, Toranomon, Hanzomon, MonzenNakacho]
  "image":    "trophy/trophy-s.jpg"
"BlockMaster":
  "nickname": "丁目マスター"
  "counts":   6
  "stations": [AoyamaItchome, GinzaItchome, ShinjukuSanchome, HongoSanchome, YotsuyaSanchome, RoppongiItchome]
  "image":    "trophy/trophy-s.jpg"
"5charsMaster":
  "nickname": "5文字以上の駅マスター"
  "counts":   17
  "stations": [AoyamaItchome, UenoHirokoji, GinzaItchome, KokkaiGijidomae, ShinOchanomizu,
               ShinjukuGyoemmae, ShinjukuSanchome, ChikatetsuAkatsuka, ChikatetsuNarimasu,
               NakanoFujimicho, HongoSanchome, MinamiAsagaya, MeijiJingumae, YotsuyaSanchome,
               YoyogiUehara, YoyogiKoen, RoppongiItchome]
  "image":    "trophy/trophy-g.jpg"
"ColorMaster":
  "nickname": "カラーマスター"
  "counts":   14
  "stations": [AoyamaItchome, Akasaka, AkasakaMitsuke, AkabaneIwabuchi, KiyosumiShirakawa,
               Ginza, GinzaItchome, Shirokanedai, ShirokaneTakanawa, ChikatetsuAkatsuka,
               NakaMeguro, HigashiGinza, Meguro]
  "image":    "trophy/trophy-g.jpg"
"AnimalMaster":
  "nickname": "アニマルマスター"
  "counts":   3
  "stations": [Toranomon, Kodemmacho, Takadanobaba]
  "image":    "trophy/trophy-s.jpg"
"ValleyMaster":
  "nickname": "谷マスター"
  "counts":   11
  "stations": [Ichigaya, Iriya, OjiKamiya, Kamiyacho, Shibuya, Zoshigaya, Hibiya, MinamiAsagaya, Myogadani, Yotsuya, YotsuyaSanchome]
  "image":    "trophy/trophy-g.jpg"
"Complete":
  "nickname": "全駅マスター"
  "counts":   143
  "stations": []
  "image":    "trophy/complete.jpg"
