"odpt.Railway:TokyoMetro.Ginza": "東京メトロ銀座線"
"odpt.Railway:TokyoMetro.Marunouchi": "東京メトロ丸ノ内線"
"odpt.Railway:TokyoMetro.Hibiya": "東京メトロ日比谷線"
"odpt.Railway:TokyoMetro.Tozai": "東京メトロ東西線"
"odpt.Railway:TokyoMetro.Chiyoda": "東京メトロ千代田線"
"odpt.Railway:TokyoMetro.Yurakucho": "東京メトロ有楽町線"
"odpt.Railway:TokyoMetro.Hanzomon": "東京メトロ半蔵門線"
"odpt.Railway:TokyoMetro.Namboku": "東京メトロ南北線"
"odpt.Railway:TokyoMetro.Fukutoshin": "東京メトロ副都心線"
